### ISSUE TITLE
Migrate project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [godiard/help-activity#26]
Please migrate this to https://github.com/sugarlabs using the migration form in https://github.com/godiard/help-activity/settings :)

**Comment by godiard** [comment]
Why? Anybody can contribute here. Or clone this repository....

**Comment by quozl** [comment]
Agreed, forked to sugarlabs.

**Comment by godiard** [comment]
@quozl, I expected collaborate with this activity at least (is clear I can't maintain all the activities I maintained working full time). If you prefer the repository at sugarlabs, I will ransfer it, I think is better than a fork.

**Comment by quozl** [comment]
@godiard, thanks, yes, I expect pull requests to come back to your repository; and this will be clear from the view of forks shown by GitHub.  No, I don't prefer your repository to be at `sugarlabs/`, but I do prefer at least a clone at `sugarlabs/` because our unqualified volunteers seem to expect to be able to find it there.  In the absence of aliases or symbolic links, this is the least bad solution.

**Comment by godiard** [comment]
Ok. Have in mind that the content in help.sugarlabs,org is generated from this repository by same magic that samdroid created with the help of a webhook.

**Comment by quozl** [comment]
@godiard, thanks, good point.

@samdroid-apps, where did you stash that magic?  Just curious, no plan to change it.
